//https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

GET http://{{host}}/api/trips/

###
POST http://{{host}}/api/spokes/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpg

< ../test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://{{host}}/api/trips/application/tId
Authentication: 'token EAADQKvzHTU0BAMZBgKzQD6fQuUU04WDcRZBWrTSvQVQeJZBKZAzVcZCkILTfjKTiuazxMW2vGu68r44HzoRxLUm4ZBionZB6tN3fCzOxA5ogNU8AvLRZCZASZCcANj7OQJ6ZAcUb8WDBMFDiPI8OrLZCfzq6j06KhQCnb3fmFHmsq2CUNsiTUDyDE78PDjdoRsK1K7ZAVwdmt9Y7iTwZDZD'


###
GET http://{{host}}/api/riders/messages/5e458ba2bfc85e039377bc48
Authentication: 'token EAADQKvzHTU0BAMZBgKzQD6fQuUU04WDcRZBWrTSvQVQeJZBKZAzVcZCkILTfjKTiuazxMW2vGu68r44HzoRxLUm4ZBionZB6tN3fCzOxA5ogNU8AvLRZCZASZCcANj7OQJ6ZAcUb8WDBMFDiPI8OrLZCfzq6j06KhQCnb3fmFHmsq2CUNsiTUDyDE78PDjdoRsK1K7ZAVwdmt9Y7iTwZDZD'