//https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

GET http://{{host}}/api/trips/

###
POST http://{{host}}/api/spokes/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpg

< ../test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://{{host}}/api/trips/application/tId
Authentication: 'token EAADQKvzHTU0BAMZBgKzQD6fQuUU04WDcRZBWrTSvQVQeJZBKZAzVcZCkILTfjKTiuazxMW2vGu68r44HzoRxLUm4ZBionZB6tN3fCzOxA5ogNU8AvLRZCZASZCcANj7OQJ6ZAcUb8WDBMFDiPI8OrLZCfzq6j06KhQCnb3fmFHmsq2CUNsiTUDyDE78PDjdoRsK1K7ZAVwdmt9Y7iTwZDZD'


###
GET http://{{host}}/api/riders/messages
Authentication: 'token EAADQKvzHTU0BAE1DLa30uWZCPqC5elfOEewlHDPtVbgS7ZAqCtvdx74iz4lYLSOTLl6BZClNj1jFrFltCqZBsYsLvTv4HnGkKymoIhvq68LFC7dBKWt3SrzzoZAYo3WkrCZCOuYZC5NlzCzK8mPkGTMzWFSfc6SuwRyrVAZCRAZBZBS9VYwLnZAH5qJWVxJCGJbZCX8ZD'

###
POST  http://{{host}}/api/riders/login HTTP/1.1
Content-Type: application/json

{"email": "jatfield@gmail.com", 
"password": "valid"}

###
GET http://{{host}}/api/riders/getresettoken/jatfield@gmail.com

###
PUT http://{{host}}/api/riders/setpassword?email=jatfield@gmail.com&password=valid
Authentication: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcG9rZXRJZCI6IjVlZjc3OTkzMGZhY2M3NDVkNDVmZDg4MiIsImlhdCI6MTYyOTI4NDc1NSwiZXhwIjoxNjI5Mjg2NTU1fQ.EWmvytk3qM1mbovxjvXe13Cvgyhiny1FXoaIqfrG4JY

###
GET http://{{host}}/api/riders/byfb/EAADQKvzHTU0BAJBmZABS5oxQMSZCav2pWhRP2lM3UEAhVUzeJC6Jr8KxpavZAYX71lIHhDFCzvKNfIzCsFjyIwHpaJIZCYmAFXIb460ZCxh8DVVtRR2CxJwnar8hFG1vBRg90F2ZBeN2mb8CCVHk3MDBUHudIrBfNYgaLVZAG59urKOmuAqqvI368bTRlgFaJ9VSMEhYHc4XgZDZD


###
GET https://api.kerekkalandok.hu/api/trips